### ISSUE TITLE
error in callback?

### ISSUE THREAD

**Issue by lopataz** [Alex7Kom/node-steam-weblogon#2]
Is there a way to get an error parameter when the web logon doesn't work?

Otherwise how can we tell if it was done well or not?

**Comment by alex7kom** [comment]
It does auto-retry until success, so the callback is only called in case of success.

**Comment by lopataz** [comment]
I see it now,
But I don't like that it's recalling it instantly? is there a way to try again after x seconds?

or is that ok if I do it like this:

```
    ....
    callback(new Error("Disconnected"));
      }.bind(this));
      return;
    }

    this.sessionID = Math.floor(Math.random() * 1000000000).toString();
    this.cookies = [
      'sessionid=' + this.sessionID,
      'steamLogin=' + body.authenticateuser.token,
      'steamLoginSecure=' + body.authenticateuser.tokensecure
    ];

    callback(null,this.sessionID, this.cookies);
     ....
```

then recall weblogon if error

**Comment by lopataz** [comment]
I personally changed the code so it returns an error in first parameter of the callback. (or null if it succeeded to logon). If we got an error, then we have choice to recall weblogon when we want, 
Because otherwise if the Steam servers are down it would go in a infernal loop of sending huge amount of requests to Steam servers.

I suggest that you change the code to include the error parameter in callback, like I did in my previous message.

**Comment by alex7kom** [comment]
This is going to be a breaking change and I want to approach it carefully.

**Comment by lopataz** [comment]
I personally use it like that:

```
      function weblogon(sessid_param) {
      if (steamClient.loggedOn && (sessid_param == null || sessid_param == "")) {
          steamsessid = "";
          steamWebLogOn.webLogOn(function(error, sessionID, newCookie) {
              if (!error) {
                  getSteamAPIKey({
                      sessionID: sessionID,
                      webCookie: newCookie
                  }, function(err, APIKey) {
                      if (!err) {
                          offers.setup({
                              sessionID: sessionID,
                              webCookie: newCookie,
                              APIKey: APIKey
                          });
                          steamsessid = sessionID;
                          console.log("offers ready!");
                          community.setCookies(newCookie);

                      } else {
                          setTimeout(function() {
                              weblogon(steamsessid);
                          }, 60000);
                      }

                  });
              } else {
                  setTimeout(function() {
                      weblogon(steamsessid);
                  }, 60000);
              }
          });

      }

  }
```

And if I need to refresh my weblogon I just do:

`if(steamsessid!=""){
    steamsessid=null;
    weblogon(steamsessid);
    }`
