### ISSUE TITLE
TypeError steam weblogon

### ISSUE THREAD

**Issue by nickbijmoer** [Alex7Kom/node-steam-weblogon#7]
Hello I got an error on this code, I dont know why, maybe u can help me :)

error: [TypeError: must start with number, buffer, array or string]

Code: 

function reWebLogOn(steam, callback) {
    steamWebLogOn.webLogOn(function(webSessionID, newCookie){
        console.log('webLogOn and webSessionID ok');
        var hash = require('crypto').createHash('sha1');
        hash.update(Math.random().toString());
        hash = hash.digest('hex');
        var device_id = 'android:' + hash;
        steamConf = new SteamConf(
        {
            steamid:         steamid,
            identity_secret: identity_secret,
            device_id:       device_id,
            webCookie:       newCookie,
        });
        getSteamAPIKey({
            sessionID: webSessionID,
            webCookie: newCookie
        }, function(err, APIKey) {
                offers.setup({
                    sessionID: webSessionID,
                    webCookie: newCookie,
                    APIKey: APIKey
                }, function(err){

```
                if (typeof callback == "function") {
                    callback();
                }

                console.log('Offers err');
            });
            steamFriends.setPersonaName(sitename+'.bot.'+botNum);
            console.log('Offers ok');
    });

});  
```

}

**Comment by alex7kom** [comment]
I don't see how this error is related to `node-steam-weblogon`. Please learn how to debug your own code.
